version: 2

services:
  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    command:  bash -c "sleep 6 && certbot certonly --standalone -d blog.fraq.io --text --agree-tos --email briggs.brenton@gmail.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt
      - /var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm
  jekyll:
    image: blog
    restart: always
    ports:
      - "80"
    volumes_from:
      - letsencrypt
  nginx:
    links:
      - letsencrypt
      - blog
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MY_DOMAIN_NAME=blog.fraq.io
